# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20161124_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=350)),
                ('size', models.IntegerField(max_length=2)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
    ]
