# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_buty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buty',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
