# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20161129_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buty',
            options={'verbose_name_plural': 'buty'},
        ),
    ]
